timestamp: "Timestamp"
attending_grand_bethel: "Are you planning to attend Grand Bethel in Visalia, CA? (Wednesday, June 17 -- Sunday, June 21)"
respondent_name: "Name"
family_attendance: "Please list names of all people in your family attending, and ages. If adult, type \"Adult\" instead of age. (Example: Jobie Example - 10 Parent Example - Adult)"
contact_phone: "Best contact phone number (text)"
emergency_contact_name: "Emergency contact's name"
emergency_contact_phone: "Emergency contact's phone number"
family_room_preference: "Do you prefer a family room with parent(s) and daughter(s) sharing a room?"
girl_adult_only_room_preference: "Do you prefer girl-only/adult-only rooms?"
bed_share_acknowledged: "If you are not sharing a family room, you will most likely need to share a bed with another individual. Please acknowledge this by clicking \"Yes\" below:"
allergies_raw: "Are there any allergies we must be aware of when planning meals and arranging roommates? (If yes, please state them here.)"
variety_show_interest: "Are you interested in participating in the Grand Bethel Variety Show?"
choir_interest: "Are you interested in performing in the Grand Bethel Choir Competition? Competition is Saturday morning of Grand Bethel."
performing_arts_interest: "Will you participate in the Performing Arts Competition?"
performing_arts_categories: "Select the category/categories you're planning to compete in:"
arts_and_crafts_interest: "Will you be participating in the Arts and Crafts Competition?"
arts_and_crafts_categories: "Select your category/categories you are planning to enter:"
librarians_report_interest: "Will you be participating in the Librarian's Report Competition?"
essay_interest: "Will you be participating in Essay Competition?"
ritual_interest: "Will you be participating in Ritual Competition?"
sew_and_show_interest: "Will you be participating in the Sew and Show Competition? There is a fashion show associated with this competition on the Grand Bethel floor (Friday afternoon)."
excursions_raw: "Are you interested in any of these excursions? Please check off all excursions you're interested in."
performing_arts_participants: "List the names of the Daughters who are participating."
performing_arts_participant_categories: "List the names of the Daughter(s) who are participating and the categories she plans to participate in."
arts_and_crafts_participant_categories: "List the names of the Daughter(s) who are participating and the categories she plans to participate in..1"
variety_show_names: "If yes to Variety Show, list the names of the Daughter(s) who are participating."
sew_and_show_names: "If yes to Sew and Show, list the name of the Daughter(s) who are participating."
choir_names: "If yes to Choir Competition, list the names of the Daughter(s) who are participating."
ritual_participant_categories: "If yes to Ritual, list the name of the Daughter(s) who are participating and the categories she wants to participate in."
essay_names: "If yes to Essay, list the name of the Daughter(s) who are participating."
librarians_report_names: "If yes to Librarian's Report, list the name of the Daughter(s) who are participating."
lunch_raw: "Please list your preferred Friday lunch option for each member of your family who is attending: Lunch Choices: Sandwiches and Salad include w/chips & fruit. All lunches come with a drink: T - Classic Turkey Sandwich H - Classic Ham Sandwich C - Chicken Strips & Fries S - Chicken Caesar Salad V - Caprese Sandwich P - Child's Pizza"
variety_show_participant_categories: "If yes to Variety Show, list the names of the Daughter(s) who are participating and the categories she plans to participate in."
